let suggestions = [
    "Dubai",
    "Sajek Valley",
    "Bali",
    "Taj Mahal",
    "Paris",
    "Egypt",
    "France",
    "Germany",
    "Italy",
    "Indonesia",
    "Japan",
    "Luxembourg",
    "Mexico",
    "Malaysia",
    "Nepal",
    "Portugal",
    "Singapore",
    "Switzerland",
    "United Arab Emirates",
    "United States",
    "United Kingdom",
    "Maldives",
    "Thailand",
];
